### ISSUE TITLE
Create customer

### ISSUE THREAD

**Issue by can-z** [can-z/pickup#6]
Using the mutation query
```graphql
mutation {
  createUser(friendlyName:"", phoneNumber:"123456789") {
    id
  }
}
```
Build a create customer page that adds customers.

**Comment by HuiFang56** [comment]
This issue is already being solved on #12.

**Comment by can-z** [comment]
what does the label "already solved on future issue" mean? It is solved in a PR and it's not a future PR.

**Comment by can-z** [comment]
also if that PR is resolved, you can close this issue because of it.

**Comment by can-z** [comment]
next time you can just link the PR to this issue so you don't even need to make that comment about it being solved by a PR (I linked it for you above).
